Vagrant.configure("2") do |config|
  # jenkins
  config.vm.define "master" do |subconfig|
    config.vm.box = "ubuntu/xenial64"
    
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    
    config.vm.provision "shell" do |shell|
      shell.path = "jenkins.sh"
    end
    
    config.vm.provider "virtualbox"
    config.vm.provision :shell, path: "bootstrap.sh"
  end

  # artifactory
  config.vm.define "master" do |subconfig|
    config.vm.box = "centos65-x86_64-20140116.box"
    
    config.vm.network "forwarded_port", guest: 8081, host: 8081
    
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../provision/artifactory.yml"
    end
    
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end

  #sonar
  config.vm.define "master" do |subconfig|
    config.vm.box = "neilus/sonar"
    
    config.vm.network "forwarded_port", guest: 9000, host: 9000

  end
end
